# Generated by Django 4.0.2 on 2022-03-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=0, help_text='13 character', max_length=13, unique=True, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default=0, help_text='Enter a brief description of the book', max_length=10000),
            preserve_default=False,
        ),
    ]
