# Generated by Django 4.0.2 on 2022-03-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='null', upload_to='books/'),
        ),
    ]
