# Generated by Django 4.0.2 on 2022-03-31 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2022, 3, 31)),
        ),
    ]
