# Generated by Django 4.0.2 on 2022-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_language_remove_book_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='select a language', to='catalog.Language'),
        ),
    ]
